### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by YNedderhoff** [nlplab/brat#1154] opened 2015-11-14 12:50 UTC
Hey, I have the problem that some lines look like this:

![untitled](https://cloud.githubusercontent.com/assets/8149019/11163569/d6dd0e24-8ad4-11e5-9d3f-b3f5eb20ccc3.png)

They obviously don't look like this in the file. It seems like there is some overlapping. I have a 1000 line file, and it starts to look like this in line 142.

Is that a known Issue? Is it a brat problem, or a corpus problem? Or could it have something to do with my OS (Ubuntu 15.10) and is unrelated to brat itself?

I don't have the problem in any other software.

**Comment by ninjin** [comment] 2015-11-14 13:53
On 14 November 2015 at 12:50, Yanick Nedderhoff
<notifications@github.com> wrote:
>
> Hey, I have the problem that some lines look like this:
>
> They obviously don't look like this in the file. It seems like there is some overlapping. I have a 1000 line file, and it starts to look like this in line 142.
>
> Is that a known Issue? Is it a brat problem, or a corpus problem? Or could it have something to do with my OS (Ubuntu 15.10) and is unrelated to brat itself?
>
> I don't have the problem in any other software.

There have been issues like this related to specific Unicode
characters, but without looking at the data it is hard to tell whether
this is the cause.  If you could construct a minimal example by
stripping down the file that is problematic, try removing all lines
apart from 141, 142, and 143 for example, we would stand a much better
chance at getting to the cause of this.

    Pontus

**Comment by YNedderhoff** [comment] 2015-11-14 15:08
Unfortunately, these are files with a Non-Disclosure-Agreement. I posted the picture because obviously you can't actually recognize anything. Is there anything I could try or look for by myself?

**Comment by ninjin** [comment] 2015-11-14 15:24
On 14 November 2015 at 15:08, Yanick Nedderhoff
<notifications@github.com> wrote:
>
> Unfortunately, these are files with a Non-Disclosure-Agreement. I posted the picture because obviously you can't actually recognize anything. Is there anything I could try or look for by myself?

Without looking at the data, the best advice we can give is:

* Delete lines to try to get a minimum amount of data that still show
    the same issue.
* Delete characters for the remaining lines to see if any specific
    character gives rise to this specific issue.
* Share any finding with us on the mailing list as we try to narrow
    down the possible causes.

Sorry to ask you to do the dirty work, but given the NDA and that
intuition is a very unwieldy debugging tool we are rather limited in
what we can do to help.

    Pontus

**Comment by YNedderhoff** [comment] 2015-11-14 15:31
Ok, it was easy to break it down to the emojis. If you remove it from the test file I appended, it works fine. Do you need any of my .conf files to test it?

Is there any way I can make brat able to handle this?

[test.txt](https://github.com/nlplab/brat/files/34646/test.txt)

**Comment by ninjin** [comment] 2015-11-14 15:42
Thank you for the debugging, it is #1115 all over again.  Closing as a dupe and discussions should proceed over at the other issue.  As it stands, we currently do not have a fix for this.

**Closed by ninjin** 2015-11-14 15:42 UTC
